apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k.image-pull-policy: Always
    k.service.type: Nodeport
  creationTimestamp: null
  labels:
    app: sparkvid-api
    release: {{ .Release.Name }}
  name: sparkvid-api
spec:
    {{ if .Values.sparkvid_api.replicaCount }}
  replicas: {{ .Values.sparkvid_api.replicaCount }}
    {{ else if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
    {{ else }}
  replicas: 1
    {{ end }}
  selector:
    matchLabels:
      app: sparkvid-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k.service.type: Nodeport
      creationTimestamp: null
      labels:
        app: sparkvid-api
    spec:
      volumes:
        - name: sparkvid-api-hostpath0
          hostPath:
            path: /app/kubehost/sparkvid/dati/
        - name: sparkvid-model-hostpath0
          hostPath:
            path: /app/kubehost/sparkvid/models/
      containers:
        - env:
            - name: spring.data.mongodb.uri
              value: {{ tpl ( index .Values.sparkvid_api.env "vid.data.mongodb.uri" ) . | quote }}
            - name: video.mongo.database
              value: {{ tpl ( index .Values.env "mongodb_sparkvid_api_database" ) . | quote }}
            - name: video.mongo.uri
              value: {{ tpl ( index .Values.env "mongodb_sparkvid_api_host" ) . | quote }}
          #image: localhost:5000/sparkvid-api:1.0.5-RELEASE
          image: "{{ tpl .Values.sparkvid_api.image.repository . }}:{{ tpl .Values.sparkvid_api.image.tag . }}"
            {{ if .Values.sparkvid_api.image.pullPolicy }}
          imagePullPolicy: "{{ tpl .Values.sparkvid_api.image.pullPolicy . }}"
            {{ else }}
          imagePullPolicy: Always
            {{ end }}
          name: sparkvidapi
          ports:
            - containerPort: {{ .Values.sparkvid_api.services.service.port }}
          resources: {}
          volumeMounts:
            - name: sparkvid-api-hostpath0
              mountPath: {{ tpl .Values.sparkvid_api.data.mountPath.vid_api . | quote }}
            - name: sparkvid-model-hostpath0
              mountPath: {{ tpl .Values.sparkvid_api.data.mountPath.vid_model . | quote }}

      restartPolicy: Always
      hostNetwork: true

status: {}
