apiVersion: v1
entries:
  chart-app-vid:
  - apiVersion: v1
    created: "2021-11-28T17:14:47.799386048+01:00"
    description: Helm Chart for movie information manager and movie advice application
    digest: fa8cc962e146cdf6a7d06dae1cca8322827d78f5efc145cae66a9915d866141f
    keywords:
    - chart-app-vid
    name: chart-app-vid
    urls:
    - https://fimperato.github.io/kubernetes-helm-chart-vid-app/charts/chart-app-vid-0.0.4.tgz
    version: 0.0.4
generated: "2021-11-28T17:14:47.799067114+01:00"
